export const semanticColors = {
  bg: {
    canvas: { value: "{colors.ocean.900}" },
    subtle: { value: "{colors.ocean.950}" },
    surface: { value: "{colors.ocean.700}" },
    panel: { value: "{colors.ocean.800}" },
    elevated: { value: "{colors.ocean.600}" },
    interactive: { value: "{colors.teal.900}" },
    overlay: { value: "rgba(3, 17, 31, 0.8)" },
  },
  fg: {
    heading: { value: "{colors.ivory.200}" },
    default: { value: "{colors.brandGray.300}" },
    muted: { value: "{colors.brandGray.400}" },
    subtle: { value: "{colors.brandGray.500}" },
    disabled: { value: "{colors.brandGray.500}" },
    inverse: { value: "{colors.ocean.900}" },
  },
  border: {
    subtle: { value: "{colors.ocean.800}" },
    default: { value: "{colors.brandBorder.100}" },
    emphasized: { value: "{colors.brandBorder.200}" },
    interactive: { value: "{colors.teal.600}" },
    focus: { value: "{colors.teal.500}" },
  },
  accent: {
    primary: { value: "{colors.teal.500}" },
    hover: { value: "{colors.teal.400}" },
    active: { value: "{colors.teal.600}" },
    subtle: { value: "{colors.teal.900}" },
    muted: { value: "{colors.teal.200}" },
    contrast: { value: "{colors.ivory.100}" },
    warm: { value: "{colors.coral.500}" },
    warmMuted: { value: "{colors.coral.300}" },
  },
  rating: {
    default: { value: "{colors.gold.500}" },
  },
  status: {
    success: { value: "{colors.teal.500}" },
    warning: { value: "{colors.coral.500}" },
    danger: { value: "#E53E3E" },
    info: { value: "{colors.teal.300}" },
  },
  brand: {
    solid: { value: "{colors.teal.500}" },
    contrast: { value: "{colors.ivory.100}" },
    fg: { value: "{colors.teal.500}" },
    muted: { value: "{colors.teal.200}" },
    subtle: { value: "{colors.teal.900}" },
    emphasized: { value: "{colors.teal.400}" },
    focusRing: { value: "{colors.teal.500}" },
  },
};
